apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appli1-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: registry.fr/soc1-appli1
    argocd-image-updater.argoproj.io/registry.fr/soc1-appli1.update-strategy: latest
    argocd-image-updater.argoproj.io/registry.fr/soc1-appli1.allow-tags: regexp:^latest$
spec:
  project: default
  source:
    repoURL: https://gitlab.com/soc1/appli1.git
    targetRevision: HEAD
    path: overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: appli1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
